site_name: PembrokePSsched
repo_url: https://github.com/jpsider/PembrokePSsched
theme: readthedocs
pages:
- Home: index.md
- PembrokePSsched Basics:
  - What is PembrokePSsched: about.md
  - Quick Start: Quick-Start-Installation-and-Example.md
- Basic Commands:
- Examples:
- Acknowledgements: acknowledgements.md
