site_name: PembrokePSsched
repo_url: https://github.com/jpsider/PembrokePSsched
theme: readthedocs
edit_uri: edit/master/docs/
pages:
- Home: index.md
- PembrokePSsched Basics:
  - What is PembrokePSsched: about.md
  - Quick Start: Quick-Start-Installation-and-Example.md
- Public Functions:
  - Invoke-DeploySched: Invoke-DeploySched.md